### ISSUE TITLE
Create engine repo

### ISSUE THREAD

**Issue by donbonifacio** [puppet-coliseum/mothership#2]
What should we call the main engine's repo? **puppet-coliseum/core**?

Things that we can add:
- Travis
- Code coverage
- Dependecy check
- Changelog

I can do this, following obb-rules as a template.

**Comment by lamuria** [comment]
@donbonifacio feel free to do it but I think that puppet-coliseum/rules or puppet-coliseum/core-rules is better because it is much more clear. I have no doubt what is in that repository

**Comment by jqmtor** [comment]
@donbonifacio , sorry for taking some time to answer here. I think this is good for starters. I don't see anything I'd like to add here.

**Comment by donbonifacio** [comment]
@lamuria @quimrstorres notice that I just auto closed this with a commit on the rules repo, :)
